addn(1,2,3)?
addn(1,2,4)?
addn(1,2,X)?
addn(1,X,4)?
addn(X,1,4)?
addn(X,Y,4)?

multn(2,4,8)?
multn(4,2,8)?
multn(5,3,X)?
multn(3,5,X)?
multn(3,X,12)?
multn(X,6,18)?

eqi(int(4,0), int(4,0))?
eqi(int(0,4), int(4,0))?
eqi(int(2,4), int(0,2))?
eqi(int(3,7), int(1,7))?

addi(int(4,0), int(0,4), int(0,0))?
addi(int(4,0), int(0,4), int(4,4))?
addi(int(4,3), int(3,1), int(2,0))?

multi(int(4,0), int(0,1), int(0,4))?
multi(int(0,4), int(2,4), int(8,0))?

inverse(int(2,6), int(4,0))?
