elem(1,[1,2,3])?
elem(3,[1,2,3])?
elem(4,[1,2,3])?
elem(X,[1,2,3])?
elem(1,[X,2,3])?

same([1,2,3],[4,5,6])?
same([1,2,3],[3,2,1])?

prefix([1,2], [1,2,3])?
prefix([1,2], [1,2])?
prefix([1,2], [1])?
prefix([1,X], [1,2,3])?
prefix([1,2], [1,X,3])?
prefix(X, [1,2,3])

append([1,2,3],[4,5,6],[1,2,3,4,5,6])?
append([1,2,3],[4,5,6],[1,2,3,6,5,4])?
append([1,X,3],[4,Y,6],[1,2,3,4,5,6])?

palindrome([])?
palindrome([1])?
palindrome([1,2])?
palindrome([1,2,1])?
